language: "ja-JP"
reviews:
  profile: "assertive"
  request_changes_workflow: true
  auto_title_placeholder: "@coderabbitai"
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!.codex/prompts"
    - "!docs/settings/"
    - "!docs/specs"
